version: '2'

services:
  ssr:
    restart: always
    image: cacaty/python
    container_name: ssr-mu
    volumes:
      - ./shadowsocksr:/shadowsocksr
    network_mode: "host"
    command: /shadowsocksr/logrun.sh
